# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='in.gore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rproduct.proto\x12\x07in.gore\x1a\x1cgoogle/api/annotations.proto\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x0eProductDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08imageUrl\x18\x02 \x01(\t2i\n\x0bProductInfo\x12Z\n\x11getProductDetails\x12\x12.in.gore.ProductId\x1a\x17.in.gore.ProductDetails\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/product/detailsb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_PRODUCTID = _descriptor.Descriptor(
  name='ProductId',
  full_name='in.gore.ProductId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='in.gore.ProductId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=79,
)


_PRODUCTDETAILS = _descriptor.Descriptor(
  name='ProductDetails',
  full_name='in.gore.ProductDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='in.gore.ProductDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='in.gore.ProductDetails.imageUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['ProductId'] = _PRODUCTID
DESCRIPTOR.message_types_by_name['ProductDetails'] = _PRODUCTDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductId = _reflection.GeneratedProtocolMessageType('ProductId', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTID,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:in.gore.ProductId)
  })
_sym_db.RegisterMessage(ProductId)

ProductDetails = _reflection.GeneratedProtocolMessageType('ProductDetails', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDETAILS,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:in.gore.ProductDetails)
  })
_sym_db.RegisterMessage(ProductDetails)



_PRODUCTINFO = _descriptor.ServiceDescriptor(
  name='ProductInfo',
  full_name='in.gore.ProductInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=131,
  serialized_end=236,
  methods=[
  _descriptor.MethodDescriptor(
    name='getProductDetails',
    full_name='in.gore.ProductInfo.getProductDetails',
    index=0,
    containing_service=None,
    input_type=_PRODUCTID,
    output_type=_PRODUCTDETAILS,
    serialized_options=b'\202\323\344\223\002\022\"\020/product/details',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTINFO)

DESCRIPTOR.services_by_name['ProductInfo'] = _PRODUCTINFO

# @@protoc_insertion_point(module_scope)
