load("//bazel/proto:def.bzl", "go_proto_library", "proto_descriptor", "proto_library", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "image_service",
    srcs = ["image.proto"],
)

proto_library(
    name = "product_service",
    srcs = ["product.proto"],
)
