# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='in.gore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bimage.proto\x12\x07in.gore\"\x1f\n\x0eProductImageId\x12\r\n\x05value\x18\x01 \x01(\t\"3\n\x0cImageDetails\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x10\n\x08imageUrl\x18\x02 \x01(\t2Q\n\x0cImageService\x12\x41\n\x0fgetImageDetails\x12\x17.in.gore.ProductImageId\x1a\x15.in.gore.ImageDetailsb\x06proto3'
)




_PRODUCTIMAGEID = _descriptor.Descriptor(
  name='ProductImageId',
  full_name='in.gore.ProductImageId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='in.gore.ProductImageId.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_IMAGEDETAILS = _descriptor.Descriptor(
  name='ImageDetails',
  full_name='in.gore.ImageDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='in.gore.ImageDetails.productId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='in.gore.ImageDetails.imageUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ProductImageId'] = _PRODUCTIMAGEID
DESCRIPTOR.message_types_by_name['ImageDetails'] = _IMAGEDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductImageId = _reflection.GeneratedProtocolMessageType('ProductImageId', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTIMAGEID,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:in.gore.ProductImageId)
  })
_sym_db.RegisterMessage(ProductImageId)

ImageDetails = _reflection.GeneratedProtocolMessageType('ImageDetails', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETAILS,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:in.gore.ImageDetails)
  })
_sym_db.RegisterMessage(ImageDetails)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='in.gore.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImageDetails',
    full_name='in.gore.ImageService.getImageDetails',
    index=0,
    containing_service=None,
    input_type=_PRODUCTIMAGEID,
    output_type=_IMAGEDETAILS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
